my_tuple = (123, 'spam', 1.23, 'francys')
print(my_tuple)
size = len(my_tuple)
print(size)
print("first element", my_tuple[0])
print("third element", my_tuple[2])
print("last element1", my_tuple[3])
print("last element2", my_tuple[size-1])
print("last element3", my_tuple[-1])
print("prelast element", my_tuple[-2])
print("first and second element", my_tuple[0:2])
print("second to third element", my_tuple[1:3])
other_tuple = (4, 5, 6)
union = my_tuple + other_tuple
print(union)