import math
# calculo de vectores
print('sea un vector a:(x,y)determinar modulo,direccion y expresar coordenadas polares')
print('ingrese valor de x')
x = float (input())
print('ingrese valor de y')
y = float (input())
modulo = round(math.sqrt((x**2)+(y**2)),2)
print('el modulo del vector (',x,',',y,') es:  ', modulo)
direccion = round(math.degrees(math.atan(y/x)),2)
print('la direccion es: ', direccion)
print('la coordenada polar es: A=(',modulo,',',direccion,')')
print('dado un vector R:(modulo,direccion) calcular los componentes')
print('ingrese valor del modulo')
modulo = float (input())
print('ingrese valor de la direccion')
direccion = float (input())
angulo = 180-direccion
Rx = round(modulo*math.cos(math.radians(angulo)),2)
Ry = round(modulo*math.sin(math.radians(angulo)),2)
print('los componentes del vector R (',modulo,',',direccion,') es:  ')
print('Rx = ', Rx)
print('Ry = ', Ry)
print('dado el vector S:(x,y,z)determinar modulo,cosenos directores y vector unitario')
print('ingrese valor de x')
x = float (input())
print('ingrese valor de y')
y = float (input())
print('ingrese valor de z')
z = float (input())
modulo = round(math.sqrt((x**2)+(y**2)+(z**2)),2)
print('el modulo del vector (',x,',',y,',',z,') es:  ', modulo)
alfa = round(math.degrees(math.acos(x/modulo)),2)
beta = round(math.degrees(math.acos(y/modulo)),2)
tita = round(math.degrees(math.acos(z/modulo)),2)
print('los cosenos directores son: ')
print('alfa: ',alfa)
print('beta: ',beta)
print('tita: ',tita)
print('el vector unitario es U =(',x,'/',modulo,',',y,'/',modulo,',',z,'/',modulo,')')